"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["client.py"]
DATA_FILES = [('', ['snd']),
              ('', ['font']),
              ('', ['img']),
              ('', ['map']),
              'entities.py',
              'network.py',
              'settings.py',
              'tilemap.py',
              'widgets.py',
              ]
OPTIONS = {
    'iconfile':'appicon.icns',
    'argv_emulation': True,
    'packages': ['pytmx', 'pytweening', 'pygame',],
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
